// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwF-MWshLm8fByUrFILdXwxQUI2gLBChs',
    appId: '1:47865968728:web:1f759e24ca6e640f70322d',
    messagingSenderId: '47865968728',
    projectId: 'ecommerceapp-f643b',
    authDomain: 'ecommerceapp-f643b.firebaseapp.com',
    storageBucket: 'ecommerceapp-f643b.firebasestorage.app',
    measurementId: 'G-C4CR1JNVPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV3N05My3JeFE1u03MQdvv8kKzspiuNjc',
    appId: '1:47865968728:android:e21b60246ddaa09870322d',
    messagingSenderId: '47865968728',
    projectId: 'ecommerceapp-f643b',
    storageBucket: 'ecommerceapp-f643b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyMrTKakahy8IKez5pioZHNzlHAq157Uc',
    appId: '1:47865968728:ios:e13020308921920a70322d',
    messagingSenderId: '47865968728',
    projectId: 'ecommerceapp-f643b',
    storageBucket: 'ecommerceapp-f643b.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyMrTKakahy8IKez5pioZHNzlHAq157Uc',
    appId: '1:47865968728:ios:e13020308921920a70322d',
    messagingSenderId: '47865968728',
    projectId: 'ecommerceapp-f643b',
    storageBucket: 'ecommerceapp-f643b.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwF-MWshLm8fByUrFILdXwxQUI2gLBChs',
    appId: '1:47865968728:web:709d622746daebaa70322d',
    messagingSenderId: '47865968728',
    projectId: 'ecommerceapp-f643b',
    authDomain: 'ecommerceapp-f643b.firebaseapp.com',
    storageBucket: 'ecommerceapp-f643b.firebasestorage.app',
    measurementId: 'G-GKKJVGMRJL',
  );
}
